import type { Product } from "./types";

export const MOCK_PRODUCTS: Product[] = [
    {
        id: "1",
        sku: "RV-AVC-001",
        name: "Ravelle Airflex Vacuum Cleaner",
        price: 598900,
        msrp: 798900,
        badge: "NEW",
        minOrder: 5,
        stock: 450,
        category: "Home Living",
        image: "https://images.unsplash.com/photo-1558317374-067fb5f30001?w=500&q=80",
        inStock: true,
        features: ["HEPA Filter", "Cordless", "2h Battery"],
        description: "Vacuum cleaner cordless dengan teknologi HEPA filter untuk pembersihan maksimal.",
    },
    {
        id: "2",
        sku: "RV-SOL-002",
        name: "Ravelle SOLIS Dehumidifier & Air Purifier 2in1 2L",
        price: 1399900,
        msrp: 1799900,
        badge: "PREMIUM",
        minOrder: 3,
        stock: 120,
        category: "Home Living",
        image: "https://www.ravelle.co.id/data/product_cover/224-20250520175323.png",
        inStock: true,
        features: ["2-in-1", "Smart Sensor", "Ultra Quiet"],
        description: "Dehumidifier dan air purifier 2 in 1 dengan smart sensor otomatis.",
    },
    {
        id: "3",
        sku: "RV-HSD-003",
        name: "Ravelle High Speed Hair Dryer",
        price: 799900,
        msrp: 899900,
        badge: null,
        minOrder: 6,
        stock: 210,
        category: "Personal Care",
        image: "https://www.ravelle.co.id/data/product_cover/207-20250109102859.png",
        inStock: true,
        features: ["Digital Display", "Auto Shutoff", "Portable"],
        description: "Hair dryer berkecepatan tinggi dengan teknologi digital untuk hasil terbaik.",
    },
    {
        id: "4",
        sku: "RV-LUX-004",
        name: "Ravelle Luxe Air Purifier HEPA13 + Anti-Allergen",
        price: 1199900,
        msrp: 1499900,
        badge: "PREMIUM",
        minOrder: 3,
        stock: 85,
        category: "Home Living",
        image: "https://www.ravelle.co.id/data/product_cover/223-20250520175032.png",
        inStock: true,
        features: ["HEPA13", "Anti-Allergen", "Smart Mode"],
        description: "Air purifier premium HEPA13 yang mampu menyaring 99.97% partikel allergen.",
    },
    {
        id: "5",
        sku: "RV-EZY-005",
        name: "Ravelle Ezy Squeenze Citrus Juicer - Cream",
        price: 559900,
        msrp: 749900,
        badge: "NEW",
        minOrder: 10,
        stock: 300,
        category: "Kitchen",
        image: "https://www.ravelle.co.id/data/product_cover/218-20250520162617.png",
        inStock: true,
        features: ["Compact", "Easy Clean", "Anti-drip"],
        description: "Juicer compact dengan desain elegan untuk dapur modern.",
    },
    {
        id: "6",
        sku: "RV-SRC-006",
        name: "Ravelle Smart Rice Cooker 1.8L",
        price: 899900,
        msrp: 1199900,
        badge: "LIMITED",
        minOrder: 5,
        stock: 95,
        category: "Kitchen",
        image: "https://cdn.ruparupa.io/fit-in/850x850/filters:format(webp)/filters:watermark(content.ruparupa.io,products/wm/rr.png,0,-0,0,100,100)/ruparupa-com/image/upload/Products/10632435_1.jpg",
        inStock: true,
        features: ["Smart Cook", "Keep Warm", "Non-stick"],
        description: "Rice cooker pintar dengan teknologi smart cook untuk hasil nasi sempurna.",
    },
    {
        id: "7",
        sku: "RV-BLD-007",
        name: "Ravelle Premium Blender 2L",
        price: 699900,
        msrp: 899900,
        badge: null,
        minOrder: 6,
        stock: 167,
        category: "Kitchen",
        image: "https://images.unsplash.com/photo-1570222094114-d054a817e56b?w=500&q=80",
        inStock: true,
        features: ["800W Motor", "Glass Jar", "6 Speeds"],
        description: "Blender premium dengan motor 800W untuk hasil blending sempurna.",
    },
    {
        id: "8",
        sku: "RV-KNF-008",
        name: "Ravelle Professional Knife Set 8pcs",
        price: 1299900,
        msrp: 1799900,
        badge: "PREMIUM",
        minOrder: 3,
        stock: 60,
        category: "Kitchen",
        image: "https://images.unsplash.com/photo-1593618998160-e34014e67546?w=500&q=80",
        inStock: true,
        features: ["German Steel", "Ergonomic", "Block Included"],
        description: "Set pisau profesional 8 pieces dengan material German steel berkualitas tinggi.",
    },
    {
        id: "9",
        sku: "RV-KNF-009",
        name: "Ravelle Professional Knife Set 8pcs",
        price: 1299900,
        msrp: 1799900,
        badge: "PREMIUM",
        minOrder: 3,
        stock: 60,
        category: "Kitchen",
        image: "https://images.unsplash.com/photo-1593618998160-e34014e67546?w=500&q=80",
        inStock: true,
        features: ["German Steel", "Ergonomic", "Block Included"],
        description: "Set pisau profesional 8 pieces dengan material German steel berkualitas tinggi.",
    },
    {
        id: "10",
        sku: "RV-KNF-010",
        name: "Ravelle Professional Knife Set 8pcs",
        price: 1299900,
        msrp: 1799900,
        badge: "PREMIUM",
        minOrder: 3,
        stock: 60,
        category: "Kitchen",
        image: "https://images.unsplash.com/photo-1593618998160-e34014e67546?w=500&q=80",
        inStock: true,
        features: ["German Steel", "Ergonomic", "Block Included"],
        description: "Set pisau profesional 8 pieces dengan material German steel berkualitas tinggi.",
    },
];

export const CATEGORIES = [
    "All Products",
    "Home & Kitchen Appliance",
    "Knife set",
    "ezy series",
    "home living",
    "keyboard",
] as const;